server:
  port: 9001
spring:
  profiles:
    active: dev
  application:
    name: cloud-payment
  main:
    allow-bean-definition-overriding: true
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
#    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
#    content-type: text/html


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    # 设置eureka实例名称
    instance-id: cloudpayment9001
    prefer-ip-address: true
    # 发送心跳间隔，默认30s
    lease-renewal-interval-in-seconds: 5


logging:
  level:
    com.wenc.springcloud.payment.feign.DemoFeignClient: debug
